persistence false
listener 1883

# Mude para true caso queira testar sem usuário/senha
# e comente o password_file caso não esteja usando
listener_allow_anonymous false
password_file /mosquitto/config/password_file